import { describe, expect, it } from 'vitest';
import { extractInputsV7Fast } from '../src/engine/katago/featuresV7Fast';
import { BLACK, BOARD_AREA, BOARD_SIZE, EMPTY, WHITE, computeAreaMapV7KataGo, setBoardSize } from '../src/engine/katago/fastBoard';

// ---------------------------------------------------------------------------
// Golden values recorded by KataGo itself, from cpp/tests/results/runOutputTests.txt
// (generated by cpp/tests/testnninputs.cpp). Unlike the hand-derived checks
// elsewhere, these are the numbers KataGo's own binary printed.
//
// The rules dump sweeps 72 rulesets; only two of them are ones this port models --
// Chinese as KO_SIMPLE / AREA / TAX_NONE and Japanese as KO_SIMPLE / TERRITORY /
// TAX_SEKI, both without suicide or a button. It runs on an empty board with black
// to move, komi 1, and a draw worth 0.47 of a win to white.
// ---------------------------------------------------------------------------

const KATAGO_DRAW_EQUIVALENT = 0.47;

const globalsFor = (size: number, rules: 'chinese' | 'japanese') => {
  setBoardSize(size);
  return extractInputsV7Fast({
    stones: new Uint8Array(BOARD_AREA),
    koPoint: -1,
    currentPlayer: 'black',
    recentMoves: [],
    komi: 1,
    rules,
    drawEquivalentWinsForWhite: KATAGO_DRAW_EQUIVALENT,
  }).global;
};

const expectGlobals = (actual: Float32Array, expected: number[]) => {
  expect(actual.length).toBe(expected.length);
  for (let i = 0; i < expected.length; i++) {
    expect(`${i}:${actual[i]!.toFixed(4)}`).toBe(`${i}:${expected[i]!.toFixed(4)}`);
  }
};

describe("KataGo's recorded rules globals", () => {
  // A komi of 1 is an integer, so the game can be drawn and the draw utility is
  // folded in: white's komi becomes 1 - 0.03, black sees -0.97, and -0.97/20 is
  // the -0.0485 KataGo printed.
  it('matches on 7x7, where the board has an odd number of points', () => {
    expectGlobals(
      globalsFor(7, 'chinese'),
      [0, 0, 0, 0, 0, -0.0485, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.03]
    );
    expectGlobals(
      globalsFor(7, 'japanese'),
      [0, 0, 0, 0, 0, -0.0485, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
    );
  });

  it('matches on 6x6, where the parity wave comes out the other way', () => {
    // Same komi, same rules: only the parity of the board area differs, and the
    // wave flips sign. This is the check that pins which way round it goes.
    expectGlobals(
      globalsFor(6, 'chinese'),
      [0, 0, 0, 0, 0, -0.0485, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.03]
    );
    expectGlobals(
      globalsFor(6, 'japanese'),
      [0, 0, 0, 0, 0, -0.0485, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
    );
  });

  it('leaves the komi alone when a draw is worth exactly half a win', () => {
    // Which is KataGo's default, and this app's: no adjustment at all.
    setBoardSize(7);
    const plain = extractInputsV7Fast({
      stones: new Uint8Array(BOARD_AREA),
      koPoint: -1,
      currentPlayer: 'black',
      recentMoves: [],
      komi: 1,
      rules: 'chinese',
    }).global;
    expect(plain[5]).toBeCloseTo(-1 / 20, 6);
  });

  it('leaves a half-integer komi alone whatever a draw is worth', () => {
    // No jigo is possible, so there is no draw utility to fold in.
    setBoardSize(7);
    const halfInteger = extractInputsV7Fast({
      stones: new Uint8Array(BOARD_AREA),
      koPoint: -1,
      currentPlayer: 'black',
      recentMoves: [],
      komi: 1.5,
      rules: 'chinese',
      drawEquivalentWinsForWhite: KATAGO_DRAW_EQUIVALENT,
    }).global;
    expect(halfInteger[5]).toBeCloseTo(-1.5 / 20, 6);
  });
});

// ---------------------------------------------------------------------------
// The area feature (planes 18 and 19), from the "Area Komi" dump in the same file.
// A 7x7 position with black to move under Tromp-Taylor, where multi-stone suicide
// is legal and so pass-alive life is judged accordingly.
// ---------------------------------------------------------------------------

const AREA_POSITION = [
  '.XO.OO.',
  'XXO.XOX',
  'OOOOOOO',
  'XXX..XX',
  '..XOOX.',
  '..XXXXX',
  '..XO.OX',
];
// Channel 18 is the mover's area, channel 19 the opponent's, exactly as printed.
const PLA_AREA = '0000000000000000000001110011111001111111111111111';
const OPP_AREA = '1111111111111111111110000000000110000000000000000';

describe("KataGo's recorded area feature", () => {
  it('agrees point for point on a settled 7x7 board', () => {
    setBoardSize(7);
    const stones = new Uint8Array(BOARD_AREA);
    AREA_POSITION.forEach((row, y) => {
      [...row].forEach((c, x) => {
        if (c === 'X') stones[y * BOARD_SIZE + x] = BLACK;
        else if (c === 'O') stones[y * BOARD_SIZE + x] = WHITE;
      });
    });

    // Tromp-Taylor allows multi-stone suicide, which changes what counts as
    // pass-alive, so the recorded run has it on.
    const area = computeAreaMapV7KataGo(stones, true);
    for (let p = 0; p < BOARD_AREA; p++) {
      const expected = PLA_AREA[p] === '1' ? BLACK : OPP_AREA[p] === '1' ? WHITE : EMPTY;
      expect(`${p % 7},${(p / 7) | 0}=${area[p]}`).toBe(`${p % 7},${(p / 7) | 0}=${expected}`);
    }
  });
});
